name: Run tests

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:
  workflow_dispatch:

concurrency:
  # group by workflow and ref; the last slightly strange component ensures that for pull
  # requests, we limit to 1 concurrent job, but for the master branch we don't
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  # Cancel intermediate builds, but only if it is a pull request build.
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    name: Test Julia ${{ matrix.julia-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        julia-version:
          # - '1.12-nightly'
          - '1.11'
          - '1.10'
          - '1.9'
          - '1.8'
          - '1.7'
          - '1.6'
          - '1.5'
          - '1.4'
          - '1.3'
          - '1.2'
          - '1.1'
          - '1.0'
          - 'nightly'
        include:
          - os: windows-latest
            julia-version: '1'
          - os: windows-latest
            julia-version: '1.0'
          # - os: windows-latest
          #   julia-version: '1.12-nightly'
          - os: windows-latest
            julia-version: 'nightly'
          - os: macOS-latest
            julia-version: '1'
          - os: macOS-13 # macOS-14 and later require julia >= 1.8
            julia-version: '1.0'
          # - os: macOS-latest
          #   julia-version: '1.12-nightly'
          - os: macOS-latest
            julia-version: 'nightly'

    steps:
      - uses: actions/checkout@v3
      - name: Setup julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v3
        with:
          file: ./lcov.info
          flags: unittests
          name: codecov-umbrella
