name: Run tests

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        julia-version: ['1.5', '1.4', '1.3', '1.2', '1.1', '1.0', 'nightly']
        include:
          - os: windows-latest
            julia-version: 1
          - os: windows-latest
            julia-version: '1.0'
      fail-fast: false
    name: Test Julia ${{ matrix.julia-version }} ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: ./lcov.info
          flags: unittests
          name: codecov-umbrella
